CREATE TABLE IF NOT EXISTS USERS(

    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE

);

CREATE TABLE IF NOT EXISTS PASSWORDS(

    user_id BIGINT PRIMARY KEY REFERENCES USERS (id) ON DELETE CASCADE,
    password VARCHAR(50) NOT NULL,
    old_password VARCHAR(50) NOT NULL


);

CREATE TABLE IF NOT EXISTS USERS_INFORMATION(

    user_id BIGINT PRIMARY KEY REFERENCES USERS (id) ON DELETE CASCADE,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    phone VARCHAR(50) NOT NULL UNIQUE

);

CREATE TABLE IF NOT EXISTS USER_ADDRESS(

    id SERIAL PRIMARY KEY,
    country VARCHAR(20) NOT NULL,
    city VARCHAR(20) NOT NULL,
    address VARCHAR(70) NOT NULL,
    user_id BIGINT REFERENCES USERS (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS USER_CREDIT_CARDS(

    id SERIAL PRIMARY KEY,
    card_number VARCHAR(20) NOT NULL,
    card_holder VARCHAR(50) NOT NULL,
    expiration_month INT NOT NULL,
    expiration_year INT NOT NULL,
    cvv NUMERIC(3,0) NOT NULL,
    user_id BIGINT REFERENCES USERS (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS CATEGORY(

    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE

);

CREATE TABLE IF NOT EXISTS PRODUCTS(

    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    quantity BIGINT NOT NULL,
    sale NUMERIC(3,0) NOT NULL DEFAULT 0,
    photo VARCHAR(80) NOT NULL,
    category_id BIGINT REFERENCES CATEGORY (id)

);

CREATE TABLE IF NOT EXISTS REVIEWS(

    id SERIAL PRIMARY KEY,
    review NUMERIC(1,1) NOT NULL DEFAULT 0,
    comment TEXT,
    review_date DATE NOT NULL,
    product_id BIGINT REFERENCES PRODUCTS (id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES USERS (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS USER_WISHLIST(

    id SERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES USERS (id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES PRODUCTS (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS HISTORY(

    id SERIAL PRIMARY KEY,
    buy_date DATE NOT NULL,
    quantity INT NOT NULL,
    total_price NUMERIC(10,2),
    user_id BIGINT REFERENCES USERS (id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES PRODUCTS (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS CART(

    id SERIAL PRIMARY KEY,
    quantity INT NOT NULL,
    user_id BIGINT REFERENCES USERS (id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES PRODUCTS (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS PRODUCT_WISHLIST(

    id SERIAL PRIMARY KEY,
    wishlist_id BIGINT REFERENCES USER_WISHLIST (id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES PRODUCTS (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS PRODUCT_HISTORY(

    id SERIAL PRIMARY KEY,
    history_id BIGINT REFERENCES HISTORY (id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES PRODUCTS (id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS PRODUCT_CART(

    id SERIAL PRIMARY KEY,
    cart_id BIGINT REFERENCES CART (id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES PRODUCTS (id) ON DELETE CASCADE

);